dist: bionic
language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - coverage=no phpunit=^8.3
  matrix:
    - setup=basic
    - setup=basic phpunit=^9.0
    - setup=stable
    - setup=stable phpunit=^9.0
    - setup=lowest
    - setup=lowest phpunit=^9.0

before_install:
  - travis_retry composer self-update
  - composer config discard-changes true

before_script:
  - composer require "phpunit/phpunit=${phpunit}" --prefer-dist --no-interaction --no-suggest
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --prefer-dist --no-interaction --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-lowest --prefer-stable; fi
  - if [[ $setup = 'coveralls' ]]; then travis_retry composer require "php-coveralls/php-coveralls=^2.1" --prefer-dist --no-interaction --no-suggest --dev; fi

script:
  - if [[ $coverage = 'yes' ]]; then ./vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml; fi
  - if [[ $coverage = 'no' ]]; then ./vendor/bin/phpunit -c phpunit.xml --testdox --verbose; fi

after_script:
  - if [[ $setup = 'coveralls' ]]; then php vendor/bin/php-coveralls -v; fi

matrix:
  include:
    - php: 7.2
      env: setup=coveralls coverage=yes
  allow_failures:
    - env: setup=coveralls coverage=yes
  fast_finish: true
